"""
Django settings for myfinancialapp project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Dosya yollarını birleştirmek için eklendi
from decouple import config # API anahtarlarını .env dosyasından okumak için eklendi

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%c*13x%2kkhj)drg+(&!f#tv5algx=^tmema%4i(p&ueecuayg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Kendi uygulamalarınız buraya eklenecek
    'analysis',        # Finansal analiz uygulamanızın adı
    #'news_sentiment',  # Haber ve duyarlılık analizi uygulamanızın adı  -şimdilik yorum satırı olarak bıraktım
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myfinancialapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS listesi, Django'nun uygulama klasörleri dışındaki ek şablon dizinlerini aramasını sağlar.
        # Genellikle proje kök dizinindeki 'templates' klasörü buraya eklenir.
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # <-- Burası güncellendi
        'APP_DIRS': True, # Bu, Django'nun INSTALLED_APPS'daki her uygulamanın kendi 'templates' klasörüne bakmasını sağlar.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myfinancialapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr' # Türkçe dil kodu olarak güncelleyebilirsiniz. 'en-us' de kalabilir.

TIME_ZONE = 'Europe/Istanbul' # Türkiye saati için 'Europe/Istanbul' olarak güncelleyebilirsiniz. 'UTC' de kalabilir.

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Django'nun statik dosyaları nerede arayacağını belirtir.
# Projenizin kök dizininde (manage.py ile aynı yerde) 'static' adında bir klasör oluşturun.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # <-- Bu satır eklendi
]

# Canlı sunucuya dağıtım yaparken, tüm statik dosyaların toplanacağı yer.
# Geliştirme aşamasında zorunlu değil, ancak gelecekte dağıtım için önemlidir.
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# API Anahtarları ve Diğer Uygulama Sabitleri
# .env dosyasından okunacak şekilde yapılandırıldı.
# config() fonksiyonu, ortam değişkenlerini veya .env dosyasındaki değerleri okur.
# İkinci parametre (default=''), eğer anahtar bulunamazsa kullanılacak varsayılan değerdir.
# Kendi anahtarlarınızı .env dosyasına yazmayı unutmayın!
COINAPI_API_KEY = config('COINAPI_API_KEY', default='')
FIXER_API_KEY = config('FIXER_API_KEY', default='')
NEWS_API_KEY = config('NEWS_API_KEY', default='')

# Modelleriniz ve özellik mühendisliğiniz için kullandığınız sabitler
# Bu değerlere artık from django.conf import settings ile erişebilirsiniz.
FEATURE_LAG = 7
TARGET_LAG = 1
VOLATILITY_THRESHOLD = 0.005 
TREND_FLATNESS_THRESHOLD = 0.0001
STABILITY_WINDOW = 20


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

