#[connections.sqlite]
#url = "sqlite:///altin_verileri_streamlit.db"

# GoldAPI.io için API Anahtarınız
GOLD_API_KEY="goldapi-8t25psmcboi8n5-io"

COINAPI_API_KEY="f970d607-417d-4767-a532-39c637b4edaa"

# NewsAPI.org için API Anahtarınız 
NEWS_API_KEY="151bb830586e47879edc74544b713f88" 

# Fixer API Anahtarınız 
FIXER_API_KEY="7e0984ecf4a9866e00e32f9ba4fef74b"